## CLEANING WITH PANDAS

### Proceso de limpieza del csv de la web scrapeada

In [4]:
import pandas as pd         
import numpy as np

In [6]:
df_filter = pd.read_csv('../scraping_data/df_filter.csv')

In [7]:
df_filter

,Unnamed: 0,Marca de la moto,Modelo,Precio de la moto,Tipo de Carné,Tipo de moto,Versión / Año,Web del fabricante,Cilindrada,Potencia Máxima Declarada,Altura asiento
0,0,Aprilia,SR GT 125 2022,3.999 €,A1,Scooter,2022,www.aprilia.com,124 cc,15 cv,799 mm
1,0,Aprilia,Tuono 660 Factory 2022,10.999 €,A,Naked,2022,www.aprilia.com/es_ES/,659 cc,100 cv,820 mm
2,0,Aprilia,Tuareg 660 Evocative 2022,12.699 €,A,Trail,2022,www.aprilia.com/es_ES/,659 cc,80 cv,860 mm
3,0,Aprilia,Tuareg 660 2022,11.999 €,A,Trail,2022,www.aprilia.com/es_ES/,659 cc,80 cv,860 mm
4,0,Aprilia,RX 125 2021,3.999 €,A1,Naked,2021,http://www.aprilia.com/es_ES/,124 cc,15 cv,880 mm
...,...,...,...,...,...,...,...,...,...,...,...
628,0,KTM,690 Duke,7.990 €,A2,Naked,2016,www.ktm.com,690 cc,73 cv,835 mm
629,0,KTM,1190 Adventure,15.599 €,A,Trail,2013,www.ktm.com,1.195 cc,150 cv,860 mm
630,0,KTM,690 Duke R,9.750 €,A,Naked,2016,www.ktm.com,690 cc,70 cv,865 mm
631,0,KTM,1190 Adventure R,16.599 €,A,Trail,2013,www.ktm.com,1.195 cc,150 cv,890 mm
632,0,KTM,RC 125,4.399 €,A1,Deportiva,2015,www.ktm.com,125 cc,15 cv,820 mm